name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main  # You can specify the branch you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get install git-lfs

    - name: Sync Hugging Face Space
      run: |
        git lfs install
        git push https://$MLOPSECRET@huggingface.co/spaces/ymalviya@wpi.edu/Mlops.git
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.MLOPSECRET }}
